name = "yetti-instant-api"
main = "src/worker.ts"
compatibility_date = "2026-10-07"

# Cloudflare D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "yetti-db"
database_id = "1adca35a-69e2-47b4-bc3a-1622f7b49677"
